### ISSUE TITLE
No herbs

### ISSUE THREAD

**Issue by Holmbatri** [t-mart/ItemVersion#24]
### What version of ItemVersion are you running?

Itemversion v2022.38.0

### What is your issue?

All Shadowland herbs show the wrong expansion in the tooltip. e.g. The version 8.2.0.30918 and expansion Battle of Azeroth is displayed for the rise in fame.

### Can you provide any screenshots of what you describe?

![grafik](https://user-images.githubusercontent.com/114366977/192168892-8a8b5ec5-79a6-4e39-95e1-8d3d2ae1a112.png)

**Comment by t-mart** [comment]
Hey, thanks for writing.

Many people have left a comment like this before. The issue is that ItemVersion reports the _currently live_ version of the game in which an item was introduced, even if that item is not accessible to players.

For example, in the case you are describing, Rising Glory was introduced while BfA was currently live, even though it was not accessible until SL. You can verify this here with Wowhead's data too: [Rising Glory](https://www.wowhead.com/item=168586/rising-glory).

![image](https://user-images.githubusercontent.com/200012/192349883-c1cbfed7-ad6c-4c21-a998-5e55c149c23f.png)

Typically, my stance on this has been to not change anything because, if we did change it, the version chosen would be arbitrary.

But, enough people have commented about this that I'm reconsidering things. It's surprising to people when they see the "wrong" version and probably makes ItemVersion feel less useful.

I've opened #25 to start thinking/working on this. Stay tuned.

**Comment by t-mart** [comment]
One other thing @Holmbatri: It looks like you use a German-language version of the game?

I'm just curious, is "Version" an accurate translation? It is the same in English, and I am concerned that the translation might not be correct.

![image](https://user-images.githubusercontent.com/200012/192357755-04516ec5-c8e3-471b-ac33-a77f4f35ea82.png)
